package com.l2jwalker.character.gameobject;

public enum NpcType {

    type,
    L2Npc,
    L2Pet,
    L2BabyPet,
    L2ControlTower,
    L2FlameTower,
    L2XmassTree,
    L2EffectPoint,
    L2Monster,
    L2Chest,
    L2Decoy,
    L2EventChest,
    L2MerchantSummon,
    L2FlyMonster,
    L2SiegeSummon,
    L2TamedBeast,
    L2FestivalMonster,
    L2SepulcherMonster,
    L2PenaltyMonster,
    L2Block,
    L2FlyNpc,
    L2TerrainObject,
    L2FeedableBeast,
    L2RiftInvader,
    L2RaidBoss,
    L2FlyRaidBoss,
    L2GrandBoss,
    L2Teleporter,
    L2Merchant,
    L2Warehouse,
    L2Trainer,
    L2VillageMasterFighter,
    L2VillageMasterPriest,
    L2Guard,
    L2VillageMasterMystic,
    L2VillageMasterDElf,
    L2VillageMasterDwarf,
    L2VillageMasterOrc,
    L2PetManager,
    L2Auctioneer,
    L2ClanHallDoormen,
    L2RaceManager,
    L2Observation,
    L2SymbolMaker,
    L2DawnPriest,
    L2DuskPriest,
    L2SignsPriest,
    L2CabaleBuffer,
    L2DungeonGatekeeper,
    L2FestivalGuide,
    L2TownPet,
    L2NpcWalker,
    L2SepulcherNpc,
    L2Fisherman,
    L2Doormen,
    L2OlympiadManager,
    L2Adventurer,
    L2ClassMaster,
    L2FriendlyMob,
    L2ClanTrader,
    L2FlyTerrainObject,
    L2VillageMasterKamael,
    L2TransformManager,
    L2Defender,
    L2Artefact,
    L2CastleDoormen,
    L2CastleTeleporter,
    L2CastleBlacksmith,
    L2CastleWarehouse,
    L2CastleChamberlain,
    L2CastleWyvernManager,
    L2MercManager,
    L2ManorManager,
    L2SiegeNpc,
    L2ClanHallManager,
    L2CastleMagician,
    L2FortManager,
    L2FortSiegeNpc,
    L2FortSupportCaptain,
    L2FortLogistics,
    L2FortDoormen,
    L2FortCommander,
    L2FortBallista,
    L2FortEnvoy,
    L2FortWyvernManager,
    L2FameManager,
    L2MercenaryManager,
    L2TerritoryWard,
    L2Minion,
    L2Boss,
    L2VillageMaster,
    L2SiegeGuard,
    L2WyvernManager,
    L2Deco,
    L2WeddingManager,
    L2TvTEventNpc;

    public static NpcType get(int id) {
        if (id < 0 || id >= values().length) {
            return null;
        }
        return values()[id];
    }

    public static NpcType get(String name) {
        return valueOf(name);
    }
}


